/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScreeningId = IDL.Text;
export const Time = IDL.Int;
export const Screening = IDL.Record({
  'id' : ScreeningId,
  'title' : IDL.Text,
  'date' : Time,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'trailerLinks' : IDL.Vec(IDL.Text),
  'posterImages' : IDL.Vec(IDL.Text),
});
export const Error = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Text,
  'internalError' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const SeatId = IDL.Text;
export const SeatStatus = IDL.Variant({
  'reserved' : IDL.Null,
  'booked' : IDL.Null,
  'available' : IDL.Null,
});
export const Seat = IDL.Record({
  'id' : SeatId,
  'row' : IDL.Text,
  'status' : SeatStatus,
  'number' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ReservationStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Reservation = IDL.Record({
  'customerName' : IDL.Text,
  'status' : ReservationStatus,
  'contactInfo' : IDL.Text,
  'seatIds' : IDL.Vec(SeatId),
  'userId' : IDL.Opt(IDL.Principal),
  'screeningId' : ScreeningId,
});
export const Result_6 = IDL.Variant({
  'ok' : IDL.Vec(IDL.Tuple(IDL.Text, Reservation)),
  'err' : Error,
});
export const UserProfile = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
});
export const Result_5 = IDL.Variant({ 'ok' : Reservation, 'err' : Error });
export const Result_4 = IDL.Variant({
  'ok' : IDL.Vec(Reservation),
  'err' : Error,
});
export const Result_3 = IDL.Variant({ 'ok' : Screening, 'err' : Error });
export const Result_2 = IDL.Variant({
  'ok' : IDL.Vec(IDL.Tuple(IDL.Text, Seat)),
  'err' : Error,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : Error });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addScreening' : IDL.Func([Screening], [Result], []),
  'addSeat' : IDL.Func([ScreeningId, Seat], [Result], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [Result], []),
  'cancelReservation' : IDL.Func([IDL.Text], [Result], []),
  'confirmReservation' : IDL.Func([IDL.Text], [Result], []),
  'createSeatPlan' : IDL.Func([ScreeningId], [Result], []),
  'deleteScreening' : IDL.Func([ScreeningId], [Result], []),
  'editScreening' : IDL.Func([ScreeningId, Screening], [Result], []),
  'getAllReservations' : IDL.Func([], [Result_6], ['query']),
  'getAllScreenings' : IDL.Func([], [IDL.Vec(Screening)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReservation' : IDL.Func([IDL.Text], [Result_5], ['query']),
  'getReservationsByScreening' : IDL.Func([IDL.Text], [Result_4], ['query']),
  'getScreening' : IDL.Func([ScreeningId], [Result_3], ['query']),
  'getSeatPlan' : IDL.Func([ScreeningId], [Result_2], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBlocked' : IDL.Func([IDL.Principal], [Result_1], ['query']),
  'makeReservation' : IDL.Func([IDL.Text, Reservation], [Result], []),
  'removeSeat' : IDL.Func([ScreeningId, SeatId], [Result], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleSeatStatus' : IDL.Func([ScreeningId, SeatId], [Result], []),
  'unblockUser' : IDL.Func([IDL.Principal], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScreeningId = IDL.Text;
  const Time = IDL.Int;
  const Screening = IDL.Record({
    'id' : ScreeningId,
    'title' : IDL.Text,
    'date' : Time,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'trailerLinks' : IDL.Vec(IDL.Text),
    'posterImages' : IDL.Vec(IDL.Text),
  });
  const Error = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Text,
    'internalError' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const SeatId = IDL.Text;
  const SeatStatus = IDL.Variant({
    'reserved' : IDL.Null,
    'booked' : IDL.Null,
    'available' : IDL.Null,
  });
  const Seat = IDL.Record({
    'id' : SeatId,
    'row' : IDL.Text,
    'status' : SeatStatus,
    'number' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ReservationStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Reservation = IDL.Record({
    'customerName' : IDL.Text,
    'status' : ReservationStatus,
    'contactInfo' : IDL.Text,
    'seatIds' : IDL.Vec(SeatId),
    'userId' : IDL.Opt(IDL.Principal),
    'screeningId' : ScreeningId,
  });
  const Result_6 = IDL.Variant({
    'ok' : IDL.Vec(IDL.Tuple(IDL.Text, Reservation)),
    'err' : Error,
  });
  const UserProfile = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
  });
  const Result_5 = IDL.Variant({ 'ok' : Reservation, 'err' : Error });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Vec(Reservation), 'err' : Error });
  const Result_3 = IDL.Variant({ 'ok' : Screening, 'err' : Error });
  const Result_2 = IDL.Variant({
    'ok' : IDL.Vec(IDL.Tuple(IDL.Text, Seat)),
    'err' : Error,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : Error });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addScreening' : IDL.Func([Screening], [Result], []),
    'addSeat' : IDL.Func([ScreeningId, Seat], [Result], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [Result], []),
    'cancelReservation' : IDL.Func([IDL.Text], [Result], []),
    'confirmReservation' : IDL.Func([IDL.Text], [Result], []),
    'createSeatPlan' : IDL.Func([ScreeningId], [Result], []),
    'deleteScreening' : IDL.Func([ScreeningId], [Result], []),
    'editScreening' : IDL.Func([ScreeningId, Screening], [Result], []),
    'getAllReservations' : IDL.Func([], [Result_6], ['query']),
    'getAllScreenings' : IDL.Func([], [IDL.Vec(Screening)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReservation' : IDL.Func([IDL.Text], [Result_5], ['query']),
    'getReservationsByScreening' : IDL.Func([IDL.Text], [Result_4], ['query']),
    'getScreening' : IDL.Func([ScreeningId], [Result_3], ['query']),
    'getSeatPlan' : IDL.Func([ScreeningId], [Result_2], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBlocked' : IDL.Func([IDL.Principal], [Result_1], ['query']),
    'makeReservation' : IDL.Func([IDL.Text, Reservation], [Result], []),
    'removeSeat' : IDL.Func([ScreeningId, SeatId], [Result], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleSeatStatus' : IDL.Func([ScreeningId, SeatId], [Result], []),
    'unblockUser' : IDL.Func([IDL.Principal], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };