/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Reservation {
  'customerName' : string,
  'status' : ReservationStatus,
  'contactInfo' : string,
  'seatIds' : Array<SeatId>,
  'screeningId' : ScreeningId,
}
export type ReservationStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface Screening {
  'id' : ScreeningId,
  'title' : string,
  'date' : Time,
  'time' : string,
  'description' : string,
  'trailerLinks' : Array<string>,
  'posterImages' : Array<string>,
}
export type ScreeningId = string;
export interface Seat {
  'id' : SeatId,
  'row' : string,
  'status' : SeatStatus,
  'number' : bigint,
}
export type SeatId = string;
export type SeatStatus = { 'reserved' : null } |
  { 'booked' : null } |
  { 'available' : null };
export type Time = bigint;
export interface UserProfile { 'contactInfo' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addScreening' : ActorMethod<[Screening], undefined>,
  'addSeat' : ActorMethod<[ScreeningId, Seat], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelReservation' : ActorMethod<[string], undefined>,
  'confirmReservation' : ActorMethod<[string], undefined>,
  'createSeatPlan' : ActorMethod<[ScreeningId], undefined>,
  'deleteScreening' : ActorMethod<[ScreeningId], undefined>,
  'editScreening' : ActorMethod<[ScreeningId, Screening], undefined>,
  'getAllReservations' : ActorMethod<[], Array<[string, Reservation]>>,
  'getAllScreenings' : ActorMethod<[], Array<Screening>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReservation' : ActorMethod<[string], Reservation>,
  'getReservationsByScreening' : ActorMethod<[string], Array<Reservation>>,
  'getScreening' : ActorMethod<[ScreeningId], Screening>,
  'getSeatPlan' : ActorMethod<[ScreeningId], Array<[string, Seat]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAdminRole' : ActorMethod<[Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'makeReservation' : ActorMethod<[string, Reservation], undefined>,
  'removeSeat' : ActorMethod<[ScreeningId, SeatId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleSeatStatus' : ActorMethod<[ScreeningId, SeatId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];