/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScreeningId = IDL.Text;
export const Time = IDL.Int;
export const Screening = IDL.Record({
  'id' : ScreeningId,
  'title' : IDL.Text,
  'date' : Time,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'trailerLinks' : IDL.Vec(IDL.Text),
  'posterImages' : IDL.Vec(IDL.Text),
});
export const SeatId = IDL.Text;
export const SeatStatus = IDL.Variant({
  'reserved' : IDL.Null,
  'booked' : IDL.Null,
  'available' : IDL.Null,
});
export const Seat = IDL.Record({
  'id' : SeatId,
  'row' : IDL.Text,
  'status' : SeatStatus,
  'number' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ReservationStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Reservation = IDL.Record({
  'customerName' : IDL.Text,
  'status' : ReservationStatus,
  'contactInfo' : IDL.Text,
  'seatIds' : IDL.Vec(SeatId),
  'screeningId' : ScreeningId,
});
export const UserProfile = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addScreening' : IDL.Func([Screening], [], []),
  'addSeat' : IDL.Func([ScreeningId, Seat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelReservation' : IDL.Func([IDL.Text], [], []),
  'confirmReservation' : IDL.Func([IDL.Text], [], []),
  'createSeatPlan' : IDL.Func([ScreeningId], [], []),
  'deleteScreening' : IDL.Func([ScreeningId], [], []),
  'editScreening' : IDL.Func([ScreeningId, Screening], [], []),
  'getAllReservations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Reservation))],
      ['query'],
    ),
  'getAllScreenings' : IDL.Func([], [IDL.Vec(Screening)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReservation' : IDL.Func([IDL.Text], [Reservation], ['query']),
  'getReservationsByScreening' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getScreening' : IDL.Func([ScreeningId], [Screening], ['query']),
  'getSeatPlan' : IDL.Func(
      [ScreeningId],
      [IDL.Vec(IDL.Tuple(IDL.Text, Seat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeReservation' : IDL.Func([IDL.Text, Reservation], [], []),
  'removeSeat' : IDL.Func([ScreeningId, SeatId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleSeatStatus' : IDL.Func([ScreeningId, SeatId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScreeningId = IDL.Text;
  const Time = IDL.Int;
  const Screening = IDL.Record({
    'id' : ScreeningId,
    'title' : IDL.Text,
    'date' : Time,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'trailerLinks' : IDL.Vec(IDL.Text),
    'posterImages' : IDL.Vec(IDL.Text),
  });
  const SeatId = IDL.Text;
  const SeatStatus = IDL.Variant({
    'reserved' : IDL.Null,
    'booked' : IDL.Null,
    'available' : IDL.Null,
  });
  const Seat = IDL.Record({
    'id' : SeatId,
    'row' : IDL.Text,
    'status' : SeatStatus,
    'number' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ReservationStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Reservation = IDL.Record({
    'customerName' : IDL.Text,
    'status' : ReservationStatus,
    'contactInfo' : IDL.Text,
    'seatIds' : IDL.Vec(SeatId),
    'screeningId' : ScreeningId,
  });
  const UserProfile = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addScreening' : IDL.Func([Screening], [], []),
    'addSeat' : IDL.Func([ScreeningId, Seat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelReservation' : IDL.Func([IDL.Text], [], []),
    'confirmReservation' : IDL.Func([IDL.Text], [], []),
    'createSeatPlan' : IDL.Func([ScreeningId], [], []),
    'deleteScreening' : IDL.Func([ScreeningId], [], []),
    'editScreening' : IDL.Func([ScreeningId, Screening], [], []),
    'getAllReservations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Reservation))],
        ['query'],
      ),
    'getAllScreenings' : IDL.Func([], [IDL.Vec(Screening)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReservation' : IDL.Func([IDL.Text], [Reservation], ['query']),
    'getReservationsByScreening' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getScreening' : IDL.Func([ScreeningId], [Screening], ['query']),
    'getSeatPlan' : IDL.Func(
        [ScreeningId],
        [IDL.Vec(IDL.Tuple(IDL.Text, Seat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeReservation' : IDL.Func([IDL.Text, Reservation], [], []),
    'removeSeat' : IDL.Func([ScreeningId, SeatId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleSeatStatus' : IDL.Func([ScreeningId, SeatId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };