/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Error = { 'notAuthorized' : null } |
  { 'invalidInput' : string } |
  { 'notFound' : string } |
  { 'internalError' : string };
export interface Reservation {
  'customerName' : string,
  'status' : ReservationStatus,
  'contactInfo' : string,
  'seatIds' : Array<SeatId>,
  'userId' : [] | [Principal],
  'screeningId' : ScreeningId,
}
export type ReservationStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type Result_1 = { 'ok' : boolean } |
  { 'err' : Error };
export type Result_2 = { 'ok' : Array<[string, Seat]> } |
  { 'err' : Error };
export type Result_3 = { 'ok' : Screening } |
  { 'err' : Error };
export type Result_4 = { 'ok' : Array<Reservation> } |
  { 'err' : Error };
export type Result_5 = { 'ok' : Reservation } |
  { 'err' : Error };
export type Result_6 = { 'ok' : Array<[string, Reservation]> } |
  { 'err' : Error };
export interface Screening {
  'id' : ScreeningId,
  'title' : string,
  'date' : Time,
  'time' : string,
  'description' : string,
  'trailerLinks' : Array<string>,
  'posterImages' : Array<string>,
}
export type ScreeningId = string;
export interface Seat {
  'id' : SeatId,
  'row' : string,
  'status' : SeatStatus,
  'number' : bigint,
}
export type SeatId = string;
export type SeatStatus = { 'reserved' : null } |
  { 'booked' : null } |
  { 'available' : null };
export type Time = bigint;
export interface UserProfile { 'contactInfo' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addScreening' : ActorMethod<[Screening], Result>,
  'addSeat' : ActorMethod<[ScreeningId, Seat], Result>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], Result>,
  'cancelReservation' : ActorMethod<[string], Result>,
  'confirmReservation' : ActorMethod<[string], Result>,
  'createSeatPlan' : ActorMethod<[ScreeningId], Result>,
  'deleteScreening' : ActorMethod<[ScreeningId], Result>,
  'editScreening' : ActorMethod<[ScreeningId, Screening], Result>,
  'getAllReservations' : ActorMethod<[], Result_6>,
  'getAllScreenings' : ActorMethod<[], Array<Screening>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReservation' : ActorMethod<[string], Result_5>,
  'getReservationsByScreening' : ActorMethod<[string], Result_4>,
  'getScreening' : ActorMethod<[ScreeningId], Result_3>,
  'getSeatPlan' : ActorMethod<[ScreeningId], Result_2>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAdminRole' : ActorMethod<[Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserBlocked' : ActorMethod<[Principal], Result_1>,
  'makeReservation' : ActorMethod<[string, Reservation], Result>,
  'removeSeat' : ActorMethod<[ScreeningId, SeatId], Result>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleSeatStatus' : ActorMethod<[ScreeningId, SeatId], Result>,
  'unblockUser' : ActorMethod<[Principal], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];